# ----------------------------------------------------------------------------------------------------------------------
# Database configurations
# ----------------------------------------------------------------------------------------------------------------------
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/magnetodb
    username: magneto
    password: 12345

